### ISSUE TITLE
Migrate to libidn2?

### ISSUE THREAD

**Issue by pnax** [zonemaster/zonemaster-ldns#131]
Our current implementation uses libidn and the [libidn README](https://git.savannah.gnu.org/cgit/libidn.git/tree/README) says:

> The IDNA2003 specifications have been superseded by IDNA2008 which is
implemented by Libidn2 <https://www.gnu.org/software/libidn/#libidn2>,
and the only reasonable use of the libidn library today is to support
the historic IDNA2003 behaviour or to use Stringprep profiles.  Please
try to migrate to libidn2 wherever possible.

Should we therefore migrate to [libidn2](https://gitlab.com/libidn/libidn2)?

**Comment by matsduf** [comment]
Yes, Zonemaster should support IDNA 2008. Stringprep has been moved out of the core protocol, but parts of it are still valid. That has been incorporated in the proposed update of Basic00 (https://github.com/zonemaster/zonemaster/pull/942).

**Comment by matsduf** [comment]
Do you know if LDNS has support for `libidn2`?

**Comment by pnax** [comment]
> Do you know if LDNS has support for libidn2?

From what I've seen, the IDN support is handled by Zonemaster::LDNS:

https://github.com/zonemaster/zonemaster-ldns/blob/001a9835bbc92367f8bab4228010c62872f7ffba/include/LDNS.h#L15-L17

**Comment by pnax** [comment]
Converting from libidn: https://libidn.gitlab.io/libidn2/manual/libidn2.html#Converting-from-libidn

**Comment by matsduf** [comment]
Resolved by #113.

**Comment by matsduf** [comment]
resolved by #133
