### ISSUE TITLE
Support for Ed25519

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-ldns#51]
Add support for algo 15, a.k.a. Ed25519. This is done by enabling a build time feature switch in `ldns` (`--enable-ed25519`). When this switch is enabled `ldns` relies on `libssl` to provide APIs for Ed25519. If those APIs aren't available the ldns configure script simply prints a little warning and continues without Ed25519 support.

Add a switch to Makefile.PL to explicitly control Ed25519 support. The feature should be enabled by default. If the feature is enabled but Ed25519 is unavailable, the build should fail.

This was originally reported in dotse/zonemaster#575.

**Edit:** I originally claimed that the build fails if Ed25519 support is requested when libssl doesn't support it. I can't reproduce that behavior anymore. Must have done something wrong but now I can't figure out what.
**Edit 2:** I updated the requirements for the feature switch in response to @matsduf's comment.

**Comment by matsduf** [comment]
No, I think that the we should enable that by default because otherwise we do not meet the expectations of the test case. In the installation instructions in Zonemaster-Engine we must include installation of new version of OpenSSL.

**Comment by sandoche2k** [comment]
It seems the update to OpenSSL 1.1.1 is not straight forward.  And, it is not in our ability to add the installation instructions. 

I would rather define this issue as an upgrade, rather than a bug.

**Comment by matsduf** [comment]
It is a bug because the specifications says that we can test that. We can change the Test Case or change the code (and instructions) to remove the bug.

**Comment by mattias-p** [comment]
Fall back to checking openssl version number.

**Comment by matsduf** [comment]
The bug is also covered by #84.

**Comment by matsduf** [comment]
PR #85 will resolve this issue.

**Comment by sandoche2k** [comment]
@matsduf why the issue is not closed?

**Comment by mattias-p** [comment]
@sandoche2k I forgot to close it.
