### ISSUE TITLE
Remove Module::Install

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-ldns#53]
Should `inc::Module::Install` be removed from the source repo and dealt with as a dependency instead? The idiomatic way seems to be using `configure_requires` declarations in Makefile.PL and including META.yml in the source repo.

Pros:
 * We could remove the step to create `inc/.author` for Zonemaster::LDNS in the ReleaseProcess.
 * We don't have to maintain `inc::Module::Install` in the source repo.

Cons:
 * We'd have to add a step to make sure META.yml is up to date for Zonemaster::LDNS in the ReleaseProcess.
 * We require Module::Install 1.19 but CentOS only provides 1.06.

**Comment by sandoche2k** [comment]
@mattias-p close?
