### ISSUE TITLE
Replace Github service Travis

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-ldns#61]
Github services are deprecated. The repo uses Github service to get the Travis function. We need to update before the end-date.

https://developer.github.com/changes/2018-04-25-github-services-deprecation/
https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

**Comment by sandoche2k** [comment]
Haven't we solved this issue ?

**Comment by matsduf** [comment]
We have not done anything, but as far as I can see Travis is still working. Must investigate.

**Comment by sandoche2k** [comment]
Close @matsduf
