### ISSUE TITLE
missing file while make distcheck

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-ldns#67]
sandoche@vps323915:~/zonemaster-ldns$ make distcheck
"/usr/bin/perl" "-Iinc" "-MExtUtils::Manifest=fullcheck" -e fullcheck
No such file: META.yml

**Comment by vlevigneron** [comment]
@mattias-p Any idea why it is not created ? (is it usefull for zonemaster-ldns ?)

**Comment by mattias-p** [comment]
If you follow the [ReleaseProcess] (specifically section 5) I believe you should get the META.yml file.
META.yml is used by CPAN and I believe other tools too.

[ReleaseProcess]: https://github.com/zonemaster/zonemaster/blob/develop/docs/internal-documentation/maintenance/ReleaseProcess.md

**Comment by sandoche2k** [comment]
fixed by following the link provided by @mattias-p
