### ISSUE TITLE
Module/Install/XSUtil.pm not found while compiling LDNS module

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-ldns#75]
Can't locate Module/Install/XSUtil.pm in @INC (@INC contains: inc /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at Makefile.PL line 8.
BEGIN failed--compilation aborted at Makefile.PL line 8

**Comment by sandoche2k** [comment]
Could be solved by adding "Module::Install::XSUtil" to the installation of ZM engine. I will add a PR for that

**Comment by matsduf** [comment]
You should follow the installation instructions for Engine first (develop branch) and then install/compile Zonemaster-LDNS. Did you?

**Comment by sandoche2k** [comment]
Yes, I did install all libraries before compiling LDNS
