### ISSUE TITLE
DNSSEC failure when using algo 15

### ISSUE THREAD

**Issue by klaver** [zonemaster/zonemaster-ldns#84]
Tested with domain: ed25519.nl
https://www.zonemaster.net/result/4a6dafd847b4f337

**Edit:** Updated the link to make up for a change in the URL scheme at zonemaster.net. /@mattias-p

**Comment by matsduf** [comment]
This issue covers the same bug as in #51, but with new information on LDNS.

**Comment by matsduf** [comment]
PR #85 will resolve this issue.

**Comment by matsduf** [comment]
Resolved by #85.
