### ISSUE TITLE
sudo cpanm Zonemaster-LDNS-2.0.1.tar.gz fails - CentOS 7

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-ldns#91]
```
--> Working on Zonemaster-LDNS-2.0.1.tar.gz
Fetching file:///home/sandoche/Zonemaster-LDNS-2.0.1.tar.gz
-> OK
Unpacking Zonemaster-LDNS-2.0.1.tar.gz
Entering Zonemaster-LDNS-2.0.1
Checking configure dependencies from META.yml
Checking if you have Devel::CheckLib 0.4 ... Yes (0.99)
Checking if you have ExtUtils::MakeMaker 6.59 ... Yes (6.68)
Checking if you have ExtUtils::ParseXS 3.18 ... Yes (3.18)
Checking if you have Devel::PPPort 3.19 ... Yes (3.20)
Checking if you have Module::Install 1.19 ... Yes (1.19)
Checking if you have Module::Install::XSUtil 0 ... Yes (0.45)
Configuring Zonemaster-LDNS-2.0.1
Running Makefile.PL
Writing ppport.h
Feature Ed25519 enabled
Can't link/include C library 'crypto', aborting.
-> N/A
-> FAIL Configure failed for Zonemaster-LDNS-2.0.1. See /root/.cpanm/work/1572517307.27860/build.log for details.
```

**Comment by mattias-p** [comment]
CentOS 7 comes with an OpenSSL that doesn't support Ed25519. For whatever reason we chose not to auto-detect Ed25519 but instead force the user to explicitly disable Ed25519 in Zonemaster-LDNS if OpenSSL doesn't provide it. You can disable it by adding `--configure-args="--no-ed25519"` to the cpanm command.

**Comment by sandoche2k** [comment]
Then it should be updated to the installation intstructions?

**Comment by mattias-p** [comment]
Yes. It should be possible to keep Ed25519 support on in CentOS 8 though.

**Comment by mattias-p** [comment]
@sandoche2k Could this be closed? I believe this was solved in zonemaster/zonemaster#821.

**Comment by matsduf** [comment]
@sandoche2k, can you take another look at this?

**Comment by sandoche2k** [comment]
It will be closed once the https://github.com/zonemaster/zonemaster-engine/blob/CentOS-Install-Update/docs/Installation.md is merged

**Comment by matsduf** [comment]
> It will be closed once the https://github.com/zonemaster/zonemaster-engine/blob/CentOS-Install-Update/docs/Installation.md is merged

What PR will install that?

**Comment by sandoche2k** [comment]
Closing this after testing
