### ISSUE TITLE
CDNSKEY fatal error

### ISSUE THREAD

**Issue by fanf2** [zonemaster/zonemaster-ldns#98]
When I run Zonemaster I sometimes get:

```
CRITICAL: Fatal error in Zonemaster::Test::Nameserver: Can't
locate object method "type" via package "Net::LDNS::RR::CDNSKEY" at
/usr/share/perl5/Zonemaster/Test/Nameserver.pm line 397.
```

It seems to work OK despite the scary error.

I have not been able to work out how to trigger it reliably: it doesn't always happen for the same zone, and it doesn't appear to be related to whether the zone has CDNSKEY records or not.

**Comment by matsduf** [comment]
@fanf2, it looks like you are running an old version of Zonemaster. Two years ago the code moved to Zonemaster::Engine, i.e. Zonemaster::Engine::Test::Nameserver. There is no Zonemaster.pm any more. Can you please check what version of Zonemaster you are running? Please consider upgrading.

**Comment by matsduf** [comment]
@fanf2, do you have more information or another question or could I close this?

**Comment by sandoche2k** [comment]
@matsduf close?

**Comment by matsduf** [comment]
No action.
